# Generated by Django 6.0.7 on 2026-07-21 18:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_bookissue_event_exam_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.institution')),
            ],
            options={
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('subject_type', models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab'), ('Practical', 'Practical')], default='Theory', max_length=10)),
                ('year', models.CharField(blank=True, max_length=50)),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.institution')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['year', 'semester', 'name'],
            },
        ),
    ]
