# Generated by Django 6.0.7 on 2026-07-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('accountant', 'Accountant'), ('librarian', 'Librarian'), ('faculty', 'Faculty'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
