# Generated by Django 6.0.7 on 2026-07-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('chairman', 'Chairman'), ('director', 'Director'), ('hod', 'Head of Department'), ('faculty', 'Faculty'), ('student', 'Student'), ('librarian', 'Librarian'), ('accountant', 'Accountant')], default='student', max_length=20),
        ),
    ]
